var wpsolr_ajax_timer;Array.prototype.remove=function(value){if(this.indexOf(value)!==-1){this.splice(this.indexOf(value),1);return true;}else{return false;}}
function generateUrlParameters(url,current_parameters,is_remove_unused_parameters){var url1=new Url(url);var force_clear_url=false;jQuery.each(current_parameters,function(key,value){if(key.substring(0,'wpsolr_'.length)!=='wpsolr_'){url1.query[key]=value;}});var query=current_parameters[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_S];if(undefined!==query){url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_S]=query||'';force_clear_url=true;}
var query=current_parameters[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_Q]||'';if(query!==''){url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_Q]=query;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_Q];}
for(var index=0;;index++){if(undefined===url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ+'['+index+']']){break;}else{delete url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ+'['+index+']'];}}
if(!force_clear_url){var query_fields=current_parameters[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ]||[];for(var index in query_fields){url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ+'['+index+']']=query_fields[index];}}
var sort=current_parameters[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SORT]||'';if((!force_clear_url)&&(sort!=='')){url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SORT]=sort;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SORT];}
var paged=current_parameters[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_PAGE]||'';if(paged!==''){url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_PAGE]=paged;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_PAGE];}
delete url1.query[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SEARCH];return '?'+url1.query.toString();}
window.addEventListener("popstate",function(e){if(e.state){call_ajax_search_timer(window.location.search,false,true);}});function get_ui_facets_state(){state=[];jQuery('.select_opt.checked').each(function(){var facet_id=jQuery(this).attr('id');var facet_data=jQuery(this).data('wpsolr-facet-data');if((facet_id!=='wpsolr_remove_facets')&&(undefined!==facet_data)&&!facet_data.is_permalink){var value='';switch(facet_data.type){case 'facet_type_range':value=facet_data.id+':'+facet_data.item_value;break;default:value=facet_data.id+':'+facet_data.item_value;break;}
state.push(value);}});jQuery('.select_opt.unchecked').each(function(){opts=jQuery(this).attr('id').split(':')[0]+':';state.push(opts);});return state;}
function get_ui_selection(){var result={};result[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_Q]=jQuery('#search_que').val()||'';result[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ]=get_ui_facets_state();result[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SORT]=jQuery('.select_field').val()||'';result[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_PAGE]=jQuery('#paginate').val()||'';return result;}
function wpsolr_ajax_loading(container,action){var loader_options={};container.LoadingOverlay(action,loader_options);}
function call_ajax_search_timer(selection_parameters,is_change_url,is_scroll_top_after){jQuery('#res_facets').append('<!-- wpsolr loading -->');if(wp_localize_script_autocomplete.data.is_ajax){var current_results=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_results).first();wpsolr_ajax_loading(current_results,'show');}
if(''!==wp_localize_script_autocomplete.data.ajax_delay_ms){if(undefined!==wpsolr_ajax_timer){window.clearTimeout(wpsolr_ajax_timer);}
wpsolr_ajax_timer=window.setTimeout(call_ajax_search,wp_localize_script_autocomplete.data.ajax_delay_ms,selection_parameters,is_change_url,is_scroll_top_after);}else{call_ajax_search(selection_parameters,is_change_url,is_scroll_top_after);}}
function call_ajax_search(selection_parameters,is_change_url,is_scroll_top_after){var url_parameters=selection_parameters;if((selection_parameters instanceof Object)&&(undefined===selection_parameters['url'])){var parameters=get_ui_selection();jQuery.extend(parameters,selection_parameters);url_parameters=generateUrlParameters(window.location.href,parameters,true);}
if(!(selection_parameters instanceof Object)||(undefined===selection_parameters['url'])){var url_base=window.location.href.split("?")[0];var url=url_base.replace(/\/page\/\d+/,'');}else{var url=selection_parameters['url'];url_parameters='';}
if(!wp_localize_script_autocomplete.data.is_ajax){window.location.href=url+url_parameters;return;}
if(is_change_url&&wp_localize_script_autocomplete.data.is_show_url_parameters&&(undefined!==window.history.pushState)){var state={url:url+url_parameters};window.history.pushState(state,'',state.url);}
var data={action:'return_solr_results',url_parameters:url_parameters};var current_page_title=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_page_title);var current_page_sort=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_page_sort);var current_count=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_results_count);var current_results=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_results).first();var current_pagination=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_pagination);jQuery.ajax({url:url+url_parameters,dataType:'html',success:function(response){var response_results=jQuery(response).find(wp_localize_script_autocomplete.data.css_ajax_container_results).first().html();if(undefined===response_results){window.location.href=url+url_parameters;}else{wpsolr_ajax_loading(current_results,'hide');var response_page_title=jQuery(response).find(wp_localize_script_autocomplete.data.css_ajax_container_page_title).first().html();var response_page_sort=jQuery(response).find(wp_localize_script_autocomplete.data.css_ajax_container_page_sort).first().html();var response_pagination=jQuery(response).find(wp_localize_script_autocomplete.data.css_ajax_container_pagination).first().html();var response_count=jQuery(response).find(wp_localize_script_autocomplete.data.css_ajax_container_results_count).first().html();jQuery(document).find('title').html(jQuery(response).filter('title').html());jQuery('meta').each(function(){var attribute=jQuery(this).attr('name')?'name':(jQuery(this).attr('property')?'property':'');if(''!==attribute){jQuery(this).attr('content',jQuery(response).filter('meta['+attribute+'="'+jQuery(this).attr(attribute)+'"]').attr('content'));}});jQuery('#res_facets').html(jQuery(response).find('#res_facets').first().html());current_page_title.html(response_page_title);current_page_sort.html(response_page_sort);current_results.html(undefined===response_results?'':response_results);current_count.html(response_count);if(undefined!==response_pagination){if(current_pagination.length===0){}
current_pagination.html(response_pagination).show();}else{current_pagination.hide();}
if(is_scroll_top_after){jQuery('html,body').animate({scrollTop:0},"fast");}
jQuery(document).trigger('wpsolr_on_ajax_success');}},error:function(){wpsolr_ajax_loading(current_results,'hide');jQuery(document).trigger('wpsolr_on_ajax_error');},always:function(){}});}
jQuery(document).ready(function(){jQuery(wp_localize_script_autocomplete.data.wpsolr_autocomplete_selector).off();jQuery(wp_localize_script_autocomplete.data.wpsolr_autocomplete_selector).prop('autocomplete','off');jQuery(document).on('focus',wp_localize_script_autocomplete.data.wpsolr_autocomplete_selector,function(event){event.preventDefault();var wp_ajax_action=wp_localize_script_autocomplete.data.wpsolr_autocomplete_action;var wp_ajax_nonce=jQuery(wp_localize_script_autocomplete.data.wpsolr_autocomplete_nonce_selector).val();var mythis=this;jQuery(this).typeahead({ajax:{url:wp_localize_script_autocomplete.data.ajax_url,triggerLength:1,method:"post",loadingClass:"loading-circle",preDispatch:function(query){jQuery(mythis).addClass('loading_sugg');return{action:wp_ajax_action,word:query,security:wp_ajax_nonce}},preProcess:function(data){jQuery(mythis).removeClass('loading_sugg');return data;}}});});if((wp_localize_script_autocomplete.data.is_ajax)&&(0===jQuery(document).find('.search-frm').length)){jQuery('form').on('submit',function(event){var me=jQuery(this);var current_results=jQuery(wp_localize_script_autocomplete.data.css_ajax_container_results).first();if(current_results.length&&jQuery(this).find(wp_localize_script_autocomplete.data.wpsolr_autocomplete_selector).length){event.preventDefault();var keywords=me.find(wp_localize_script_autocomplete.data.wpsolr_autocomplete_selector).first().attr("value");var parameter={};if(''!==wp_localize_script_autocomplete.data.redirect_search_home){parameter['url']='/'+wp_localize_script_autocomplete.data.redirect_search_home+'/'+keywords.toLowerCase().trim().replace(/ +/g," ").replace(/ /g,'+').replace(/\++/g,"+");}else{parameter[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_S]=keywords;}
call_ajax_search_timer(parameter,true,true);}});jQuery(document).off('change',wp_localize_script_autocomplete.data.css_ajax_container_page_sort+' select');jQuery(wp_localize_script_autocomplete.data.css_ajax_container_page_sort).closest('form').on('submit',function(){return false;});jQuery(document).on('change',wp_localize_script_autocomplete.data.css_ajax_container_page_sort+' select',function(event){var me=jQuery(this);event.preventDefault();var parameter={};parameter[me.attr("name")]=me.attr("value");call_ajax_search_timer(parameter,true,true);});jQuery(document).on('click',wp_localize_script_autocomplete.data.css_ajax_container_pagination_page,function(event){event.preventDefault();var me=jQuery(this);var parameter={};parameter['url']=me.attr("href");call_ajax_search_timer(parameter,true,true);});}
window.wpsolr_facet_change=function($items,event){jQuery('#paginate').val('');var state=[];var $this;$items.each(function(index){$this=jQuery(this);var facet_data=$this.data('wpsolr-facet-data');if($this.attr('id')==='wpsolr_remove_facets'){jQuery('.select_opt').removeClass('checked');$this.addClass('checked');}else{is_already_selected=$this.hasClass('checked')&&('facet_type_min_max'!==facet_data.type);var facet_name=$this.attr('id').split(":")[0];if(is_already_selected){$this.removeClass('checked');$this.addClass('unchecked');$this.next("ul").children().find("[id^="+facet_name+"]").removeClass('checked');if($this.hasClass('wpsolr_facet_option')){if($this.parent().prop("multiple")){var current_level=$this.data('wpsolr-facet-data').level;$this.nextAll().each(function(){if(current_level<jQuery(this).data('wpsolr-facet-data').level){jQuery(this).removeClass('checked');}else{return false;}});}}}else{$this.closest("ul.wpsolr_facet_radiobox").children().find("[id^="+facet_name+"]").removeClass('checked');if($this.hasClass('wpsolr_facet_option')){if(!$this.parent().prop("multiple")){$this.parent().children().removeClass('checked');}else{var current_selected_level=$this.data('wpsolr-facet-data').level;$this.prevAll().each(function(){if(current_selected_level>jQuery(this).data('wpsolr-facet-data').level){jQuery(this).addClass('checked');current_selected_level=jQuery(this).data('wpsolr-facet-data').level;}});}
$this.addClass('checked');}else{$this.parents("li").children(".select_opt").addClass('checked');}}
state=get_ui_facets_state();}})
var parameter={};var permalink;if(undefined!==$this){permalink=$this.find('a.wpsolr_permalink').first().attr('href')||$this.data('wpsolr-facet-data').permalink_href;}
if(undefined===permalink){parameter[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_FQ]=state;}else{if((null!==event)&&(undefined!==event)){event.preventDefault();}
parameter['url']=permalink;}
call_ajax_search_timer(parameter,true,false);}
jQuery(document).on('click','div.select_opt',function(event){if('facet_type_field'===jQuery(this).data('wpsolr-facet-data').type){wpsolr_facet_change(jQuery(this),event);}});function wpsolr_select_value(current){var selected_values=current.val();if(current.prop('multiple')){current.children().removeClass('checked');}
wpsolr_facet_change(current.find('option:selected'),event);}
jQuery(document).on('change','.wpsolr_facet_select select',function(event){wpsolr_select_value(jQuery(this));});jQuery(document).on('clickx','.wpsolr_facet_select .wpsolr-select-multiple option',function(event){wpsolr_select_value(jQuery(this).parent('select'));});jQuery(document).on('change','.select_field',function(){jQuery('#paginate').val('');sort_value=jQuery(this).val();var parameter={};parameter[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_SORT]=sort_value;call_ajax_search_timer(parameter,true,true);});jQuery(document).on('click','.paginate',function(){page_number=jQuery(this).attr('id');jQuery('#paginate').val(page_number);var parameter={};parameter[wp_localize_script_autocomplete.data.SEARCH_PARAMETER_PAGE]=page_number;call_ajax_search_timer(parameter,true,false);});jQuery(wp_localize_script_autocomplete.data.WPSOLR_FILTER_GEOLOCATION_SEARCH_BOX_JQUERY_SELECTOR).each(function(index){jQuery(this).closest('form').append(wp_localize_script_autocomplete.data.WPSOLR_FILTER_ADD_GEO_USER_AGREEMENT_CHECKBOX_TO_AJAX_SEARCH_FORM);});jQuery('form').on('submit',function(event){var me=jQuery(this);if(jQuery(this).find(wp_localize_script_autocomplete.data.WPSOLR_FILTER_GEOLOCATION_SEARCH_BOX_JQUERY_SELECTOR).length){var nb_user_agreement_checkboxes=jQuery(this).find(wp_localize_script_autocomplete.data.WPSOLR_FILTER_GEOLOCATION_USER_AGREEMENT_JQUERY_SELECTOR).length;var user_agreement_first_checkbox_value=jQuery(this).find(wp_localize_script_autocomplete.data.WPSOLR_FILTER_GEOLOCATION_USER_AGREEMENT_JQUERY_SELECTOR).filter(':checked').first().val();var current_checkbox=jQuery(this).find(wp_localize_script_autocomplete.data.WPSOLR_FILTER_GEOLOCATION_USER_AGREEMENT_JQUERY_SELECTOR).first();if(!current_checkbox.prop('checked')){me.append(jQuery("<input />").attr("type","hidden").attr("name",current_checkbox.prop("name")).val(wp_localize_script_autocomplete.data.PARAMETER_VALUE_NO));}else{current_checkbox.val(wp_localize_script_autocomplete.data.PARAMETER_VALUE_YES);}
if((0===nb_user_agreement_checkboxes)||(undefined!==user_agreement_first_checkbox_value)){if(navigator.geolocation){event.preventDefault();me.addClass("wpsolr_geo_loading");var wpsolr_geo_loading_timeout=window.setTimeout(function(){me.removeClass("wpsolr_geo_loading");},10000);navigator.geolocation.getCurrentPosition(function(position){window.clearTimeout(wpsolr_geo_loading_timeout);me.addClass("wpsolr_geo_loading");me.append(jQuery("<input />").attr("type","hidden").attr("name",wp_localize_script_autocomplete.data.SEARCH_PARAMETER_LATITUDE).val(position.coords.latitude));me.append(jQuery("<input />").attr("type","hidden").attr("name",wp_localize_script_autocomplete.data.SEARCH_PARAMETER_LONGITUDE).val(position.coords.longitude));me.unbind('submit').submit();},function(error){console.log('wpsolr: geolocation error: '+error.code);window.clearTimeout(wpsolr_geo_loading_timeout);me.addClass("wpsolr_geo_loading");me.unbind('submit').submit();});}else{console.log('wpsolr: geolocation not supported by browser.');}}}});});